version: "3"
services: 
  bend1:
    image: lucapiccinelli/bend1:latest
    ports:
      - "5000:5000"
    networks:
      - webnet1

  db1:
    image: mysql
    volumes:
      - "/home/picci/mysqldata:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - webnet1

networks:
      webnet1:
  