version: "3"
services:
  db1:
    image: mysql
    volumes:
      - "/home/picci/mysqldata3:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306

  